# Generated by Django 4.1.1 on 2022-11-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0002_alter_language_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='original',
            field=models.CharField(default='English', max_length=48),
            preserve_default=False,
        ),
    ]
