# Generated by Django 4.1.1 on 2022-10-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_query_count_words_alter_query_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='slug',
            field=models.SlugField(default='no have slug'),
        ),
    ]
