# Generated by Django 4.1.1 on 2022-10-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0003_query_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='initial',
            field=models.CharField(default='no have initial name', max_length=64),
        ),
    ]
