# Generated by Django 4.1.1 on 2022-10-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0004_word_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='initial',
            field=models.CharField(max_length=64),
        ),
    ]
