# Generated by Django 4.1.1 on 2022-10-30 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0005_alter_word_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='initial',
        ),
        migrations.AddField(
            model_name='query',
            name='active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='querytranslate',
            name='slug',
            field=models.SlugField(default='no have slug'),
        ),
        migrations.AddField(
            model_name='word',
            name='active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='word',
            name='slug',
            field=models.SlugField(default='no have slug'),
        ),
        migrations.AddField(
            model_name='wordtranslate',
            name='slug',
            field=models.SlugField(default='no have slug'),
        ),
        migrations.AlterField(
            model_name='querytranslate',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word.query'),
        ),
    ]
