# Generated by Django 4.1.1 on 2022-10-30 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('word', '0006_remove_word_initial_query_active_querytranslate_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='querytranslate',
            name='language',
        ),
        migrations.RemoveField(
            model_name='querytranslate',
            name='query',
        ),
        migrations.RemoveField(
            model_name='word',
            name='query',
        ),
        migrations.RemoveField(
            model_name='word',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='wordtranslate',
            name='slug',
        ),
        migrations.AddField(
            model_name='word',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='word',
            name='word',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='word_set', to='word.word'),
        ),
        migrations.DeleteModel(
            name='Query',
        ),
        migrations.DeleteModel(
            name='QueryTranslate',
        ),
    ]
