# Generated by Django 4.1.1 on 2022-10-31 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('word', '0007_remove_querytranslate_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='review',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='word',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='word_set', to='word.word'),
        ),
    ]
