# Generated by Django 4.1.1 on 2022-10-31 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0008_word_review_alter_word_user_alter_word_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordtranslate',
            name='sound',
            field=models.FileField(null=True, upload_to='word/sound/'),
        ),
    ]
