# Generated by Django 4.1.1 on 2022-11-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0009_alter_wordtranslate_sound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordtranslate',
            name='transcription',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
